バニッシュの処理を追加しました。
Chuzume/Chuzume-s-Toolbox pull request #1
Opened 2021-06-21 12:42 UTC by yjunchengtian

バニッシュ使用後の難易度は、ノーマルに矯正されなくなりました。
プルリクエストは初めてなので、手順に誤りがないことを祈ります。

2021-06-21 16:28 UTC, ChenCMD requested changes
外部からで申し訳ないのですが、今回の場合scoreboardを利用する必要はなく、storageで十分かと。
また、`useful_tools:return_to_normal`の関数名も同時に変更するべきです。

2021-06-22 09:59 UTC, yjunchengtian commented
コメントありがとうございます。
実は、元統合版勢なので、Java版マイクラのコマンドを使いこなせていないかもしれません。
ストレージは、保存する値が多くなり、スコアボードでの管理が難しくなった場合に使えば良いと考えていました。
次回作は保存する値が増えそうなので、ストレージを使うかもしれません。

2021-06-22 11:29 UTC, ChenCMD commented
次回作とかではなくこのPullRequestについて修正をお願いしているのですが....

2021-06-22 12:45 UTC, yjunchengtian commented
失礼しました。説明不足でしたね。
ストレージを使わないのは、コマンドの簡略化が望めないからです。
そもそもストレージは、nbtを直で保存する場合など、スコアボードでは保存・管理が難しいときに使うのもだと思います。
今回のように、保存する値の数が少ない場合は、スコアボードのほうが管理がしやすいのです。
また、前述したように元統合版勢ですので、Java版限定コマンドであるdataコマンドは、正直使いこなせません。
下手にバグを作りたくなかったので、スコアボードを使いました。
現在のプルリクエストは防具立てを使っていますが、よく考えるとこれはマルチプレイ時に問題が発生する可能性がありますね。修正します。

2021-06-23 13:12 UTC, ChenCMD commented
今現在、単一の値をentity(armor_stand)を使用してscoreboardに保存する方法は全く使われておらず、ダミープレイヤーを利用してscoreboardに保存する方法、もしくはstorageに保存する方法が一般的に使われています。

今回のケースの場合、新規にscoreboard objectを追加する程の処理には思えないためstorageを利用する方法を提案させて頂きましたが、storageでの実装が出来ないと言うことでしたらこのPullRequestはcloseし、こちらで実装させていただきますがよろしいでしょうか？

2021-06-23 21:34 UTC, yjunchengtian commented
是非お願いしたいです。プルリクエストのクローズはどのタイミングで行えばよいでしょうか？

2021-06-25 11:17 UTC, ChenCMD commented
もうしていただいても構わないです。

2021-07-14 11:46 UTC, closed without merging